# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-29 12:27
from __future__ import unicode_literals

from django.db import migrations

import csv

def load_models(apps, schema_editor):
    with open("migrate_data/models.csv", "r") as f:
        dict_reader = csv.DictReader(f)
        Model = apps.get_model("diag_app", "Model")
        for row in dict_reader:
            model_object = Model(**row)
            model_object.save()


class Migration(migrations.Migration):

    dependencies = [
        ('diag_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_models),
    ]
