# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-30 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diag_app', '0002_auto_20170829_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem_model',
            name='model',
        ),
        migrations.RemoveField(
            model_name='problem_model',
            name='problem',
        ),
        migrations.DeleteModel(
            name='Problem_Model',
        ),
    ]
