# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-23 15:51
from __future__ import unicode_literals

from django.db import migrations

import csv

def load_brands(apps, schema_editor):
    with open("migrate_data/brand.csv", "r") as f:
        dict_reader = csv.DictReader(f, fieldnames= ['value'])
        Brand = apps.get_model("diag_app", "Brand")
        for row in dict_reader:
            brand_object = Brand(**row)
            brand_object.save()


def load_years(apps, schema_editor):
    with open("migrate_data/years.csv", "r") as f:
        dict_reader = csv.DictReader(f, fieldnames= ['value'])
        Year = apps.get_model("diag_app", "Year")
        for row in dict_reader:
            year = Year(**row)
            year.save()


def load_models(apps, schema_editor):
    with open("migrate_data/model_year_id_clean.csv", "r") as f:
        dict_reader = csv.DictReader(f, delimiter= ",", fieldnames = ['brand_id','name','year_id'])
        Model = apps.get_model("diag_app", "Model")
        for row in dict_reader:
            model_object = Model(**row)
            model_object.save()



class Migration(migrations.Migration):

    dependencies = [
        ('diag_app', '0002_auto_20180123_1401'),
    ]

    operations = [
        migrations.RunPython(load_brands),
        migrations.RunPython(load_years),
        migrations.RunPython(load_models)
    ]
