# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-31 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diag_app', '0003_auto_20170830_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='job_title',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tech',
            name='shop',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
