# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-08 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diag_app', '0005_auto_20170906_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diag_app.Problem'),
        ),
    ]
