# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-25 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diag_app', '0012_auto_20170927_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='tech',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='tech',
        ),
        migrations.AddField(
            model_name='problem',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commit',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
